---

- name: Terminate instances that were previously launched
  ec2:
    region: "{{ region|default('us-west-2') }}"
    instance_ids: "{{ hostvars[groups['tag_Name_'+item.name][0]]['ec2_id'] }}"
    state: 'absent'
    wait: yes
    group: "{{ item.security_group }}"
  register: deleted_instances
  with_items: "{{ instances }}"