---

- name: Take security groups sdown
  local_action:
    module: ec2_group
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    region: "{{ region }}"
    state: 'absent'
  with_items: "{{ security_groups }}"