- name: Provision logproducer environment
  hosts: localhost
  gather_facts: false
  connection: local

  vars_files:
    - vars/aws/elk/distributed/instances.yaml
    - vars/aws/elk/distributed/security_groups.yaml

  tasks:
#    - include: tasks/aws/keypair.yaml name="ptopsworks" region="us-east-1"
    - include: tasks/aws/securitygroup.yaml region="us-east-1"
    - include: tasks/aws/instance.yaml keypair="ptopsworks" region="us-east-1"