- name: Terminate standalone elk environment
  hosts: localhost
  gather_facts: false
  connection: local

  vars_files:
    - vars/aws/standalone/standalone.yaml
    - vars/aws/standalone/aws.yaml

  tasks:
    - include: tasks/aws/instances_terminate.yaml
    - include: tasks/aws/securitygroup_terminate.yaml
    - include: tasks/aws/keypair_terminate.yaml