- name: Terminate distributed elk cluster environment
  hosts: localhost
  gather_facts: false
  connection: local

  vars_files:
    - vars/aws/distributed/distributed.yaml
    - vars/aws/distributed/aws.yaml

  tasks:
    - include: tasks/aws/instances_terminate.yaml
    - include: tasks/aws/securitygroup_terminate.yaml
    - include: tasks/aws/keypair_terminate.yaml