---

- name: sansible.users_and_groups
  src: https://github.com/sansible/users_and_groups
  version: origin/master


- name: tersmitten.logrotated
  src: https://github.com/Oefenweb/ansible-logrotated
  version: v1.2.0

- name: tersmitten.pip
  src: https://github.com/Oefenweb/ansible-pip
  version: v1.0.2

- name: dwcramer.upstart
  src: https://github.com/dwcramer/ansible-upstart
  version: 0.1.0